// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("WebApiContrib.Testing")]
[assembly: AssemblyProductAttribute("WebApiContrib")]
[assembly: AssemblyDescriptionAttribute("Community Contributions for ASP.NET Web API")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
