// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("WebApiContrib")]
[assembly: AssemblyProductAttribute("WebApiContrib")]
[assembly: AssemblyDescriptionAttribute("Community Contributions for ASP.NET Web API")]
[assembly: AssemblyCopyrightAttribute("WebApiContrib Contributors")]
[assembly: AssemblyVersionAttribute("2.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.0";
    }
}
